# Generated by Django 3.1.7 on 2021-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ManyToManyField(to='api.Company'),
        ),
    ]
